# Generated by Django 6.0.6 on 2026-06-21 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('denomination', models.CharField(max_length=50, verbose_name='Номинал')),
                ('metal', models.CharField(blank=True, max_length=50, verbose_name='Металл')),
                ('condition', models.CharField(choices=[('PF', 'Превосходное (Proof)'), ('UNC', 'Безупречное (UNC)'), ('XF', 'Отличное (XF)'), ('VF', 'Очень хорошее (VF)'), ('F', 'Хорошее (F)'), ('P', 'Плохое (P)')], default='VF', max_length=3, verbose_name='Состояние')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес (граммы)')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='Диаметр (мм)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coins/', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
                'ordering': ['-year', 'country'],
            },
        ),
    ]
